logging:
  level:
    root: WARN
    ru.chatdemo: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  messages:
    basename: messages/app

server.servlet:
  port: 8080
  contextPath: /
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true



