logging:
  level:
    root: WARN
    ru.chatdemo: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true
